// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/narwhal.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionError_CollectionErrorType int32

const (
	CollectionError_COLLECTION_NOT_FOUND CollectionError_CollectionErrorType = 0
	CollectionError_COLLECTION_TIMEOUT   CollectionError_CollectionErrorType = 1
	CollectionError_COLLECTION_ERROR     CollectionError_CollectionErrorType = 2
)

// Enum value maps for CollectionError_CollectionErrorType.
var (
	CollectionError_CollectionErrorType_name = map[int32]string{
		0: "COLLECTION_NOT_FOUND",
		1: "COLLECTION_TIMEOUT",
		2: "COLLECTION_ERROR",
	}
	CollectionError_CollectionErrorType_value = map[string]int32{
		"COLLECTION_NOT_FOUND": 0,
		"COLLECTION_TIMEOUT":   1,
		"COLLECTION_ERROR":     2,
	}
)

func (x CollectionError_CollectionErrorType) Enum() *CollectionError_CollectionErrorType {
	p := new(CollectionError_CollectionErrorType)
	*p = x
	return p
}

func (x CollectionError_CollectionErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectionError_CollectionErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_narwhal_proto_enumTypes[0].Descriptor()
}

func (CollectionError_CollectionErrorType) Type() protoreflect.EnumType {
	return &file_proto_narwhal_proto_enumTypes[0]
}

func (x CollectionError_CollectionErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectionError_CollectionErrorType.Descriptor instead.
func (CollectionError_CollectionErrorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{2, 0}
}

type CertificateDigest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *CertificateDigest) Reset() {
	*x = CertificateDigest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateDigest) ProtoMessage() {}

func (x *CertificateDigest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateDigest.ProtoReflect.Descriptor instead.
func (*CertificateDigest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateDigest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CollectionError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The collection for which this error refers to
	Id    *CertificateDigest                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error CollectionError_CollectionErrorType `protobuf:"varint,2,opt,name=error,proto3,enum=narwhal.CollectionError_CollectionErrorType" json:"error,omitempty"`
}

func (x *CollectionError) Reset() {
	*x = CollectionError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionError) ProtoMessage() {}

func (x *CollectionError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionError.ProtoReflect.Descriptor instead.
func (*CollectionError) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionError) GetId() *CertificateDigest {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CollectionError) GetError() CollectionError_CollectionErrorType {
	if x != nil {
		return x.Error
	}
	return CollectionError_COLLECTION_NOT_FOUND
}

type MultiAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *MultiAddr) Reset() {
	*x = MultiAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiAddr) ProtoMessage() {}

func (x *MultiAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiAddr.ProtoReflect.Descriptor instead.
func (*MultiAddr) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{3}
}

func (x *MultiAddr) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{4}
}

func (x *PublicKey) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type ValidatorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey      *PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	StakeWeight    int64      `protobuf:"varint,2,opt,name=stake_weight,json=stakeWeight,proto3" json:"stake_weight,omitempty"`
	PrimaryAddress *MultiAddr `protobuf:"bytes,3,opt,name=primary_address,json=primaryAddress,proto3" json:"primary_address,omitempty"`
}

func (x *ValidatorData) Reset() {
	*x = ValidatorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorData) ProtoMessage() {}

func (x *ValidatorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorData.ProtoReflect.Descriptor instead.
func (*ValidatorData) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatorData) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorData) GetStakeWeight() int64 {
	if x != nil {
		return x.StakeWeight
	}
	return 0
}

func (x *ValidatorData) GetPrimaryAddress() *MultiAddr {
	if x != nil {
		return x.PrimaryAddress
	}
	return nil
}

type Collection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The collection's id
	Id *CertificateDigest `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The transactions that are part of the collection
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *Collection) Reset() {
	*x = Collection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{6}
}

func (x *Collection) GetId() *CertificateDigest {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Collection) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CollectionRetrievalResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RetrievalResult:
	//
	//	*CollectionRetrievalResult_Collection
	//	*CollectionRetrievalResult_Error
	RetrievalResult isCollectionRetrievalResult_RetrievalResult `protobuf_oneof:"retrieval_result"`
}

func (x *CollectionRetrievalResult) Reset() {
	*x = CollectionRetrievalResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionRetrievalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionRetrievalResult) ProtoMessage() {}

func (x *CollectionRetrievalResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionRetrievalResult.ProtoReflect.Descriptor instead.
func (*CollectionRetrievalResult) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{7}
}

func (m *CollectionRetrievalResult) GetRetrievalResult() isCollectionRetrievalResult_RetrievalResult {
	if m != nil {
		return m.RetrievalResult
	}
	return nil
}

func (x *CollectionRetrievalResult) GetCollection() *Collection {
	if x, ok := x.GetRetrievalResult().(*CollectionRetrievalResult_Collection); ok {
		return x.Collection
	}
	return nil
}

func (x *CollectionRetrievalResult) GetError() *CollectionError {
	if x, ok := x.GetRetrievalResult().(*CollectionRetrievalResult_Error); ok {
		return x.Error
	}
	return nil
}

type isCollectionRetrievalResult_RetrievalResult interface {
	isCollectionRetrievalResult_RetrievalResult()
}

type CollectionRetrievalResult_Collection struct {
	Collection *Collection `protobuf:"bytes,1,opt,name=collection,proto3,oneof"`
}

type CollectionRetrievalResult_Error struct {
	Error *CollectionError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CollectionRetrievalResult_Collection) isCollectionRetrievalResult_RetrievalResult() {}

func (*CollectionRetrievalResult_Error) isCollectionRetrievalResult_RetrievalResult() {}

type GetCollectionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of collections to be retrieved.
	CollectionIds []*CertificateDigest `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *GetCollectionsRequest) Reset() {
	*x = GetCollectionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionsRequest) ProtoMessage() {}

func (x *GetCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionsRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{8}
}

func (x *GetCollectionsRequest) GetCollectionIds() []*CertificateDigest {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

type GetCollectionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO: Revisit this for spec compliance.
	// List of retrieval results of collections.
	Result []*CollectionRetrievalResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *GetCollectionsResponse) Reset() {
	*x = GetCollectionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionsResponse) ProtoMessage() {}

func (x *GetCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionsResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{9}
}

func (x *GetCollectionsResponse) GetResult() []*CollectionRetrievalResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type RemoveCollectionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of collections to be removed.
	CollectionIds []*CertificateDigest `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *RemoveCollectionsRequest) Reset() {
	*x = RemoveCollectionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionsRequest) ProtoMessage() {}

func (x *RemoveCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionsRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveCollectionsRequest) GetCollectionIds() []*CertificateDigest {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

type ReadCausalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A collection for which a sequence of related collections are to be retrieved.
	CollectionId *CertificateDigest `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
}

func (x *ReadCausalRequest) Reset() {
	*x = ReadCausalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCausalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCausalRequest) ProtoMessage() {}

func (x *ReadCausalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCausalRequest.ProtoReflect.Descriptor instead.
func (*ReadCausalRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{11}
}

func (x *ReadCausalRequest) GetCollectionId() *CertificateDigest {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

type ReadCausalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Resulting sequence of collections from DAG walk.
	CollectionIds []*CertificateDigest `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *ReadCausalResponse) Reset() {
	*x = ReadCausalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCausalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCausalResponse) ProtoMessage() {}

func (x *ReadCausalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCausalResponse.ProtoReflect.Descriptor instead.
func (*ReadCausalResponse) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{12}
}

func (x *ReadCausalResponse) GetCollectionIds() []*CertificateDigest {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

type RoundsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / The validator's key for which we want to retrieve
	// / the available rounds.
	PublicKey *PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *RoundsRequest) Reset() {
	*x = RoundsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundsRequest) ProtoMessage() {}

func (x *RoundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundsRequest.ProtoReflect.Descriptor instead.
func (*RoundsRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{13}
}

func (x *RoundsRequest) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RoundsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / The oldest round for which the node has available
	// / blocks to propose for the defined validator.
	OldestRound uint64 `protobuf:"varint,1,opt,name=oldest_round,json=oldestRound,proto3" json:"oldest_round,omitempty"`
	// / The newest (latest) round for which the node has available
	// / blocks to propose for the defined validator.
	NewestRound uint64 `protobuf:"varint,2,opt,name=newest_round,json=newestRound,proto3" json:"newest_round,omitempty"`
}

func (x *RoundsResponse) Reset() {
	*x = RoundsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundsResponse) ProtoMessage() {}

func (x *RoundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundsResponse.ProtoReflect.Descriptor instead.
func (*RoundsResponse) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{14}
}

func (x *RoundsResponse) GetOldestRound() uint64 {
	if x != nil {
		return x.OldestRound
	}
	return 0
}

func (x *RoundsResponse) GetNewestRound() uint64 {
	if x != nil {
		return x.NewestRound
	}
	return 0
}

type NodeReadCausalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey *PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Round     uint64     `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *NodeReadCausalRequest) Reset() {
	*x = NodeReadCausalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeReadCausalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReadCausalRequest) ProtoMessage() {}

func (x *NodeReadCausalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReadCausalRequest.ProtoReflect.Descriptor instead.
func (*NodeReadCausalRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{15}
}

func (x *NodeReadCausalRequest) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *NodeReadCausalRequest) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type NodeReadCausalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Resulting sequence of collections from DAG walk.
	CollectionIds []*CertificateDigest `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *NodeReadCausalResponse) Reset() {
	*x = NodeReadCausalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeReadCausalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReadCausalResponse) ProtoMessage() {}

func (x *NodeReadCausalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReadCausalResponse.ProtoReflect.Descriptor instead.
func (*NodeReadCausalResponse) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{16}
}

func (x *NodeReadCausalResponse) GetCollectionIds() []*CertificateDigest {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

type NewNetworkInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochNumber uint32           `protobuf:"varint,1,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	Validators  []*ValidatorData `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (x *NewNetworkInfoRequest) Reset() {
	*x = NewNetworkInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNetworkInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNetworkInfoRequest) ProtoMessage() {}

func (x *NewNetworkInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNetworkInfoRequest.ProtoReflect.Descriptor instead.
func (*NewNetworkInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{17}
}

func (x *NewNetworkInfoRequest) GetEpochNumber() uint32 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

func (x *NewNetworkInfoRequest) GetValidators() []*ValidatorData {
	if x != nil {
		return x.Validators
	}
	return nil
}

type NewEpochRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochNumber uint32           `protobuf:"varint,1,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	Validators  []*ValidatorData `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (x *NewEpochRequest) Reset() {
	*x = NewEpochRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEpochRequest) ProtoMessage() {}

func (x *NewEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEpochRequest.ProtoReflect.Descriptor instead.
func (*NewEpochRequest) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{18}
}

func (x *NewEpochRequest) GetEpochNumber() uint32 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

func (x *NewEpochRequest) GetValidators() []*ValidatorData {
	if x != nil {
		return x.Validators
	}
	return nil
}

type GetPrimaryAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimaryAddress *MultiAddr `protobuf:"bytes,1,opt,name=primary_address,json=primaryAddress,proto3" json:"primary_address,omitempty"`
}

func (x *GetPrimaryAddressResponse) Reset() {
	*x = GetPrimaryAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrimaryAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimaryAddressResponse) ProtoMessage() {}

func (x *GetPrimaryAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimaryAddressResponse.ProtoReflect.Descriptor instead.
func (*GetPrimaryAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{19}
}

func (x *GetPrimaryAddressResponse) GetPrimaryAddress() *MultiAddr {
	if x != nil {
		return x.PrimaryAddress
	}
	return nil
}

// Empty message for when we don't have anything to return
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_narwhal_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narwhal_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_narwhal_proto_rawDescGZIP(), []int{20}
}

var File_proto_narwhal_proto protoreflect.FileDescriptor

var file_proto_narwhal_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x22, 0x2b,
	0x0a, 0x11, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x44, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x0b, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe0, 0x01, 0x0a,
	0x0f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x2a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e,
	0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x02, 0x69, 0x64, 0x12, 0x42, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x6e, 0x61,
	0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x5d, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4c, 0x4c, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4c,
	0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22,
	0x25, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0d, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x3b, 0x0a, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x61, 0x72,
	0x77, 0x68, 0x61, 0x6c, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x64, 0x64, 0x72, 0x52, 0x0e,
	0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x72,
	0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68,
	0x61, 0x6c, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x35, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x12, 0x0a, 0x10, 0x72, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x5a, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x54, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x5d, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52,
	0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x54,
	0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x72,
	0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x0d,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x42, 0x0a,
	0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x56, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x65, 0x73,
	0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74,
	0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6e, 0x65,
	0x77, 0x65, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x60, 0x0a, 0x15, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x5b, 0x0a, 0x16, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x72, 0x0a, 0x15, 0x4e, 0x65, 0x77, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68,
	0x61, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x6c, 0x0a, 0x0f,
	0x4e, 0x65, 0x77, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x36, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x58, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x41, 0x64, 0x64, 0x72, 0x52, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xed, 0x01,
	0x0a, 0x09, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x51, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e,
	0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x21, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61,
	0x75, 0x73, 0x61, 0x6c, 0x12, 0x1a, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43,
	0x61, 0x75, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x98, 0x01,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e,
	0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c, 0x12, 0x1e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x75, 0x73, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd0, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x08, 0x4e, 0x65,
	0x77, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x18, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x2e, 0x4e, 0x65, 0x77, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x40, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x77,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x47, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x22, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x90, 0x01, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x11,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x17, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x6e, 0x61, 0x72,
	0x77, 0x68, 0x61, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_narwhal_proto_rawDescOnce sync.Once
	file_proto_narwhal_proto_rawDescData = file_proto_narwhal_proto_rawDesc
)

func file_proto_narwhal_proto_rawDescGZIP() []byte {
	file_proto_narwhal_proto_rawDescOnce.Do(func() {
		file_proto_narwhal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_narwhal_proto_rawDescData)
	})
	return file_proto_narwhal_proto_rawDescData
}

var file_proto_narwhal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_narwhal_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_narwhal_proto_goTypes = []any{
	(CollectionError_CollectionErrorType)(0), // 0: narwhal.CollectionError.CollectionErrorType
	(*CertificateDigest)(nil),                // 1: narwhal.CertificateDigest
	(*Transaction)(nil),                      // 2: narwhal.Transaction
	(*CollectionError)(nil),                  // 3: narwhal.CollectionError
	(*MultiAddr)(nil),                        // 4: narwhal.MultiAddr
	(*PublicKey)(nil),                        // 5: narwhal.PublicKey
	(*ValidatorData)(nil),                    // 6: narwhal.ValidatorData
	(*Collection)(nil),                       // 7: narwhal.Collection
	(*CollectionRetrievalResult)(nil),        // 8: narwhal.CollectionRetrievalResult
	(*GetCollectionsRequest)(nil),            // 9: narwhal.GetCollectionsRequest
	(*GetCollectionsResponse)(nil),           // 10: narwhal.GetCollectionsResponse
	(*RemoveCollectionsRequest)(nil),         // 11: narwhal.RemoveCollectionsRequest
	(*ReadCausalRequest)(nil),                // 12: narwhal.ReadCausalRequest
	(*ReadCausalResponse)(nil),               // 13: narwhal.ReadCausalResponse
	(*RoundsRequest)(nil),                    // 14: narwhal.RoundsRequest
	(*RoundsResponse)(nil),                   // 15: narwhal.RoundsResponse
	(*NodeReadCausalRequest)(nil),            // 16: narwhal.NodeReadCausalRequest
	(*NodeReadCausalResponse)(nil),           // 17: narwhal.NodeReadCausalResponse
	(*NewNetworkInfoRequest)(nil),            // 18: narwhal.NewNetworkInfoRequest
	(*NewEpochRequest)(nil),                  // 19: narwhal.NewEpochRequest
	(*GetPrimaryAddressResponse)(nil),        // 20: narwhal.GetPrimaryAddressResponse
	(*Empty)(nil),                            // 21: narwhal.Empty
}
var file_proto_narwhal_proto_depIdxs = []int32{
	1,  // 0: narwhal.CollectionError.id:type_name -> narwhal.CertificateDigest
	0,  // 1: narwhal.CollectionError.error:type_name -> narwhal.CollectionError.CollectionErrorType
	5,  // 2: narwhal.ValidatorData.public_key:type_name -> narwhal.PublicKey
	4,  // 3: narwhal.ValidatorData.primary_address:type_name -> narwhal.MultiAddr
	1,  // 4: narwhal.Collection.id:type_name -> narwhal.CertificateDigest
	2,  // 5: narwhal.Collection.transactions:type_name -> narwhal.Transaction
	7,  // 6: narwhal.CollectionRetrievalResult.collection:type_name -> narwhal.Collection
	3,  // 7: narwhal.CollectionRetrievalResult.error:type_name -> narwhal.CollectionError
	1,  // 8: narwhal.GetCollectionsRequest.collection_ids:type_name -> narwhal.CertificateDigest
	8,  // 9: narwhal.GetCollectionsResponse.result:type_name -> narwhal.CollectionRetrievalResult
	1,  // 10: narwhal.RemoveCollectionsRequest.collection_ids:type_name -> narwhal.CertificateDigest
	1,  // 11: narwhal.ReadCausalRequest.collection_id:type_name -> narwhal.CertificateDigest
	1,  // 12: narwhal.ReadCausalResponse.collection_ids:type_name -> narwhal.CertificateDigest
	5,  // 13: narwhal.RoundsRequest.public_key:type_name -> narwhal.PublicKey
	5,  // 14: narwhal.NodeReadCausalRequest.public_key:type_name -> narwhal.PublicKey
	1,  // 15: narwhal.NodeReadCausalResponse.collection_ids:type_name -> narwhal.CertificateDigest
	6,  // 16: narwhal.NewNetworkInfoRequest.validators:type_name -> narwhal.ValidatorData
	6,  // 17: narwhal.NewEpochRequest.validators:type_name -> narwhal.ValidatorData
	4,  // 18: narwhal.GetPrimaryAddressResponse.primary_address:type_name -> narwhal.MultiAddr
	9,  // 19: narwhal.Validator.GetCollections:input_type -> narwhal.GetCollectionsRequest
	11, // 20: narwhal.Validator.RemoveCollections:input_type -> narwhal.RemoveCollectionsRequest
	12, // 21: narwhal.Validator.ReadCausal:input_type -> narwhal.ReadCausalRequest
	14, // 22: narwhal.Proposer.Rounds:input_type -> narwhal.RoundsRequest
	16, // 23: narwhal.Proposer.NodeReadCausal:input_type -> narwhal.NodeReadCausalRequest
	19, // 24: narwhal.Configuration.NewEpoch:input_type -> narwhal.NewEpochRequest
	18, // 25: narwhal.Configuration.NewNetworkInfo:input_type -> narwhal.NewNetworkInfoRequest
	21, // 26: narwhal.Configuration.GetPrimaryAddress:input_type -> narwhal.Empty
	2,  // 27: narwhal.Transactions.SubmitTransaction:input_type -> narwhal.Transaction
	2,  // 28: narwhal.Transactions.SubmitTransactionStream:input_type -> narwhal.Transaction
	10, // 29: narwhal.Validator.GetCollections:output_type -> narwhal.GetCollectionsResponse
	21, // 30: narwhal.Validator.RemoveCollections:output_type -> narwhal.Empty
	13, // 31: narwhal.Validator.ReadCausal:output_type -> narwhal.ReadCausalResponse
	15, // 32: narwhal.Proposer.Rounds:output_type -> narwhal.RoundsResponse
	17, // 33: narwhal.Proposer.NodeReadCausal:output_type -> narwhal.NodeReadCausalResponse
	21, // 34: narwhal.Configuration.NewEpoch:output_type -> narwhal.Empty
	21, // 35: narwhal.Configuration.NewNetworkInfo:output_type -> narwhal.Empty
	20, // 36: narwhal.Configuration.GetPrimaryAddress:output_type -> narwhal.GetPrimaryAddressResponse
	21, // 37: narwhal.Transactions.SubmitTransaction:output_type -> narwhal.Empty
	21, // 38: narwhal.Transactions.SubmitTransactionStream:output_type -> narwhal.Empty
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_narwhal_proto_init() }
func file_proto_narwhal_proto_init() {
	if File_proto_narwhal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_narwhal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CertificateDigest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CollectionError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MultiAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ValidatorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Collection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CollectionRetrievalResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetCollectionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetCollectionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveCollectionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ReadCausalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ReadCausalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RoundsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RoundsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*NodeReadCausalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*NodeReadCausalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*NewNetworkInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*NewEpochRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetPrimaryAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_narwhal_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_narwhal_proto_msgTypes[7].OneofWrappers = []any{
		(*CollectionRetrievalResult_Collection)(nil),
		(*CollectionRetrievalResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_narwhal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_narwhal_proto_goTypes,
		DependencyIndexes: file_proto_narwhal_proto_depIdxs,
		EnumInfos:         file_proto_narwhal_proto_enumTypes,
		MessageInfos:      file_proto_narwhal_proto_msgTypes,
	}.Build()
	File_proto_narwhal_proto = out.File
	file_proto_narwhal_proto_rawDesc = nil
	file_proto_narwhal_proto_goTypes = nil
	file_proto_narwhal_proto_depIdxs = nil
}
