// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: proto/narwhal.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Validator_GetCollections_FullMethodName    = "/narwhal.Validator/GetCollections"
	Validator_RemoveCollections_FullMethodName = "/narwhal.Validator/RemoveCollections"
	Validator_ReadCausal_FullMethodName        = "/narwhal.Validator/ReadCausal"
)

// ValidatorClient is the client API for Validator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The consensus to mempool interface for validator actions.
type ValidatorClient interface {
	// Returns collection contents for each requested collection.
	GetCollections(ctx context.Context, in *GetCollectionsRequest, opts ...grpc.CallOption) (*GetCollectionsResponse, error)
	// Expunges collections from the mempool.
	RemoveCollections(ctx context.Context, in *RemoveCollectionsRequest, opts ...grpc.CallOption) (*Empty, error)
	// Returns collections along a DAG walk with a well-defined starting point.
	ReadCausal(ctx context.Context, in *ReadCausalRequest, opts ...grpc.CallOption) (*ReadCausalResponse, error)
}

type validatorClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorClient(cc grpc.ClientConnInterface) ValidatorClient {
	return &validatorClient{cc}
}

func (c *validatorClient) GetCollections(ctx context.Context, in *GetCollectionsRequest, opts ...grpc.CallOption) (*GetCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionsResponse)
	err := c.cc.Invoke(ctx, Validator_GetCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorClient) RemoveCollections(ctx context.Context, in *RemoveCollectionsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Validator_RemoveCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorClient) ReadCausal(ctx context.Context, in *ReadCausalRequest, opts ...grpc.CallOption) (*ReadCausalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCausalResponse)
	err := c.cc.Invoke(ctx, Validator_ReadCausal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorServer is the server API for Validator service.
// All implementations must embed UnimplementedValidatorServer
// for forward compatibility
//
// The consensus to mempool interface for validator actions.
type ValidatorServer interface {
	// Returns collection contents for each requested collection.
	GetCollections(context.Context, *GetCollectionsRequest) (*GetCollectionsResponse, error)
	// Expunges collections from the mempool.
	RemoveCollections(context.Context, *RemoveCollectionsRequest) (*Empty, error)
	// Returns collections along a DAG walk with a well-defined starting point.
	ReadCausal(context.Context, *ReadCausalRequest) (*ReadCausalResponse, error)
	mustEmbedUnimplementedValidatorServer()
}

// UnimplementedValidatorServer must be embedded to have forward compatible implementations.
type UnimplementedValidatorServer struct {
}

func (UnimplementedValidatorServer) GetCollections(context.Context, *GetCollectionsRequest) (*GetCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollections not implemented")
}
func (UnimplementedValidatorServer) RemoveCollections(context.Context, *RemoveCollectionsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCollections not implemented")
}
func (UnimplementedValidatorServer) ReadCausal(context.Context, *ReadCausalRequest) (*ReadCausalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCausal not implemented")
}
func (UnimplementedValidatorServer) mustEmbedUnimplementedValidatorServer() {}

// UnsafeValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidatorServer will
// result in compilation errors.
type UnsafeValidatorServer interface {
	mustEmbedUnimplementedValidatorServer()
}

func RegisterValidatorServer(s grpc.ServiceRegistrar, srv ValidatorServer) {
	s.RegisterService(&Validator_ServiceDesc, srv)
}

func _Validator_GetCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorServer).GetCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Validator_GetCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorServer).GetCollections(ctx, req.(*GetCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validator_RemoveCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorServer).RemoveCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Validator_RemoveCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorServer).RemoveCollections(ctx, req.(*RemoveCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validator_ReadCausal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCausalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorServer).ReadCausal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Validator_ReadCausal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorServer).ReadCausal(ctx, req.(*ReadCausalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Validator_ServiceDesc is the grpc.ServiceDesc for Validator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Validator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narwhal.Validator",
	HandlerType: (*ValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCollections",
			Handler:    _Validator_GetCollections_Handler,
		},
		{
			MethodName: "RemoveCollections",
			Handler:    _Validator_RemoveCollections_Handler,
		},
		{
			MethodName: "ReadCausal",
			Handler:    _Validator_ReadCausal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/narwhal.proto",
}

const (
	Proposer_Rounds_FullMethodName         = "/narwhal.Proposer/Rounds"
	Proposer_NodeReadCausal_FullMethodName = "/narwhal.Proposer/NodeReadCausal"
)

// ProposerClient is the client API for Proposer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// / The API that hosts the endpoints that should be used to help
// / proposing a block.
type ProposerClient interface {
	Rounds(ctx context.Context, in *RoundsRequest, opts ...grpc.CallOption) (*RoundsResponse, error)
	// Returns the read_causal obtained by starting the DAG walk at the collection
	// proposed by the input authority (as indicated by their public key) at the input round
	NodeReadCausal(ctx context.Context, in *NodeReadCausalRequest, opts ...grpc.CallOption) (*NodeReadCausalResponse, error)
}

type proposerClient struct {
	cc grpc.ClientConnInterface
}

func NewProposerClient(cc grpc.ClientConnInterface) ProposerClient {
	return &proposerClient{cc}
}

func (c *proposerClient) Rounds(ctx context.Context, in *RoundsRequest, opts ...grpc.CallOption) (*RoundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundsResponse)
	err := c.cc.Invoke(ctx, Proposer_Rounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposerClient) NodeReadCausal(ctx context.Context, in *NodeReadCausalRequest, opts ...grpc.CallOption) (*NodeReadCausalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeReadCausalResponse)
	err := c.cc.Invoke(ctx, Proposer_NodeReadCausal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProposerServer is the server API for Proposer service.
// All implementations must embed UnimplementedProposerServer
// for forward compatibility
//
// / The API that hosts the endpoints that should be used to help
// / proposing a block.
type ProposerServer interface {
	Rounds(context.Context, *RoundsRequest) (*RoundsResponse, error)
	// Returns the read_causal obtained by starting the DAG walk at the collection
	// proposed by the input authority (as indicated by their public key) at the input round
	NodeReadCausal(context.Context, *NodeReadCausalRequest) (*NodeReadCausalResponse, error)
	mustEmbedUnimplementedProposerServer()
}

// UnimplementedProposerServer must be embedded to have forward compatible implementations.
type UnimplementedProposerServer struct {
}

func (UnimplementedProposerServer) Rounds(context.Context, *RoundsRequest) (*RoundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rounds not implemented")
}
func (UnimplementedProposerServer) NodeReadCausal(context.Context, *NodeReadCausalRequest) (*NodeReadCausalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeReadCausal not implemented")
}
func (UnimplementedProposerServer) mustEmbedUnimplementedProposerServer() {}

// UnsafeProposerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProposerServer will
// result in compilation errors.
type UnsafeProposerServer interface {
	mustEmbedUnimplementedProposerServer()
}

func RegisterProposerServer(s grpc.ServiceRegistrar, srv ProposerServer) {
	s.RegisterService(&Proposer_ServiceDesc, srv)
}

func _Proposer_Rounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposerServer).Rounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Proposer_Rounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposerServer).Rounds(ctx, req.(*RoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proposer_NodeReadCausal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeReadCausalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposerServer).NodeReadCausal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Proposer_NodeReadCausal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposerServer).NodeReadCausal(ctx, req.(*NodeReadCausalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Proposer_ServiceDesc is the grpc.ServiceDesc for Proposer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proposer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narwhal.Proposer",
	HandlerType: (*ProposerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rounds",
			Handler:    _Proposer_Rounds_Handler,
		},
		{
			MethodName: "NodeReadCausal",
			Handler:    _Proposer_NodeReadCausal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/narwhal.proto",
}

const (
	Configuration_NewEpoch_FullMethodName          = "/narwhal.Configuration/NewEpoch"
	Configuration_NewNetworkInfo_FullMethodName    = "/narwhal.Configuration/NewNetworkInfo"
	Configuration_GetPrimaryAddress_FullMethodName = "/narwhal.Configuration/GetPrimaryAddress"
)

// ConfigurationClient is the client API for Configuration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigurationClient interface {
	// Signals a new epoch
	NewEpoch(ctx context.Context, in *NewEpochRequest, opts ...grpc.CallOption) (*Empty, error)
	// Signals a change in networking info
	NewNetworkInfo(ctx context.Context, in *NewNetworkInfoRequest, opts ...grpc.CallOption) (*Empty, error)
	// Retrieve multiaddr of narwhal primary
	GetPrimaryAddress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPrimaryAddressResponse, error)
}

type configurationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationClient(cc grpc.ClientConnInterface) ConfigurationClient {
	return &configurationClient{cc}
}

func (c *configurationClient) NewEpoch(ctx context.Context, in *NewEpochRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Configuration_NewEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) NewNetworkInfo(ctx context.Context, in *NewNetworkInfoRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Configuration_NewNetworkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) GetPrimaryAddress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPrimaryAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrimaryAddressResponse)
	err := c.cc.Invoke(ctx, Configuration_GetPrimaryAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServer is the server API for Configuration service.
// All implementations must embed UnimplementedConfigurationServer
// for forward compatibility
type ConfigurationServer interface {
	// Signals a new epoch
	NewEpoch(context.Context, *NewEpochRequest) (*Empty, error)
	// Signals a change in networking info
	NewNetworkInfo(context.Context, *NewNetworkInfoRequest) (*Empty, error)
	// Retrieve multiaddr of narwhal primary
	GetPrimaryAddress(context.Context, *Empty) (*GetPrimaryAddressResponse, error)
	mustEmbedUnimplementedConfigurationServer()
}

// UnimplementedConfigurationServer must be embedded to have forward compatible implementations.
type UnimplementedConfigurationServer struct {
}

func (UnimplementedConfigurationServer) NewEpoch(context.Context, *NewEpochRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewEpoch not implemented")
}
func (UnimplementedConfigurationServer) NewNetworkInfo(context.Context, *NewNetworkInfoRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewNetworkInfo not implemented")
}
func (UnimplementedConfigurationServer) GetPrimaryAddress(context.Context, *Empty) (*GetPrimaryAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrimaryAddress not implemented")
}
func (UnimplementedConfigurationServer) mustEmbedUnimplementedConfigurationServer() {}

// UnsafeConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServer will
// result in compilation errors.
type UnsafeConfigurationServer interface {
	mustEmbedUnimplementedConfigurationServer()
}

func RegisterConfigurationServer(s grpc.ServiceRegistrar, srv ConfigurationServer) {
	s.RegisterService(&Configuration_ServiceDesc, srv)
}

func _Configuration_NewEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).NewEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_NewEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).NewEpoch(ctx, req.(*NewEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_NewNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewNetworkInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).NewNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_NewNetworkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).NewNetworkInfo(ctx, req.(*NewNetworkInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_GetPrimaryAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetPrimaryAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetPrimaryAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetPrimaryAddress(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Configuration_ServiceDesc is the grpc.ServiceDesc for Configuration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Configuration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narwhal.Configuration",
	HandlerType: (*ConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewEpoch",
			Handler:    _Configuration_NewEpoch_Handler,
		},
		{
			MethodName: "NewNetworkInfo",
			Handler:    _Configuration_NewNetworkInfo_Handler,
		},
		{
			MethodName: "GetPrimaryAddress",
			Handler:    _Configuration_GetPrimaryAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/narwhal.proto",
}

const (
	Transactions_SubmitTransaction_FullMethodName       = "/narwhal.Transactions/SubmitTransaction"
	Transactions_SubmitTransactionStream_FullMethodName = "/narwhal.Transactions/SubmitTransactionStream"
)

// TransactionsClient is the client API for Transactions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionsClient interface {
	// Submit a Transactions
	SubmitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Empty, error)
	// Submit a Transactions
	SubmitTransactionStream(ctx context.Context, opts ...grpc.CallOption) (Transactions_SubmitTransactionStreamClient, error)
}

type transactionsClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionsClient(cc grpc.ClientConnInterface) TransactionsClient {
	return &transactionsClient{cc}
}

func (c *transactionsClient) SubmitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Transactions_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsClient) SubmitTransactionStream(ctx context.Context, opts ...grpc.CallOption) (Transactions_SubmitTransactionStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Transactions_ServiceDesc.Streams[0], Transactions_SubmitTransactionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &transactionsSubmitTransactionStreamClient{ClientStream: stream}
	return x, nil
}

type Transactions_SubmitTransactionStreamClient interface {
	Send(*Transaction) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type transactionsSubmitTransactionStreamClient struct {
	grpc.ClientStream
}

func (x *transactionsSubmitTransactionStreamClient) Send(m *Transaction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionsSubmitTransactionStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionsServer is the server API for Transactions service.
// All implementations must embed UnimplementedTransactionsServer
// for forward compatibility
type TransactionsServer interface {
	// Submit a Transactions
	SubmitTransaction(context.Context, *Transaction) (*Empty, error)
	// Submit a Transactions
	SubmitTransactionStream(Transactions_SubmitTransactionStreamServer) error
	mustEmbedUnimplementedTransactionsServer()
}

// UnimplementedTransactionsServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionsServer struct {
}

func (UnimplementedTransactionsServer) SubmitTransaction(context.Context, *Transaction) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedTransactionsServer) SubmitTransactionStream(Transactions_SubmitTransactionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubmitTransactionStream not implemented")
}
func (UnimplementedTransactionsServer) mustEmbedUnimplementedTransactionsServer() {}

// UnsafeTransactionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionsServer will
// result in compilation errors.
type UnsafeTransactionsServer interface {
	mustEmbedUnimplementedTransactionsServer()
}

func RegisterTransactionsServer(s grpc.ServiceRegistrar, srv TransactionsServer) {
	s.RegisterService(&Transactions_ServiceDesc, srv)
}

func _Transactions_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transactions_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServer).SubmitTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transactions_SubmitTransactionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionsServer).SubmitTransactionStream(&transactionsSubmitTransactionStreamServer{ServerStream: stream})
}

type Transactions_SubmitTransactionStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*Transaction, error)
	grpc.ServerStream
}

type transactionsSubmitTransactionStreamServer struct {
	grpc.ServerStream
}

func (x *transactionsSubmitTransactionStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionsSubmitTransactionStreamServer) Recv() (*Transaction, error) {
	m := new(Transaction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Transactions_ServiceDesc is the grpc.ServiceDesc for Transactions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transactions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narwhal.Transactions",
	HandlerType: (*TransactionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _Transactions_SubmitTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitTransactionStream",
			Handler:       _Transactions_SubmitTransactionStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/narwhal.proto",
}
