// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: narwhal-gateway.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NarwhalGateway_SubmitTransaction_FullMethodName        = "/narwhal_gateway.NarwhalGateway/SubmitTransaction"
	NarwhalGateway_SubscribeConsensusOutput_FullMethodName = "/narwhal_gateway.NarwhalGateway/SubscribeConsensusOutput"
	NarwhalGateway_DeliverConsensusOutput_FullMethodName   = "/narwhal_gateway.NarwhalGateway/DeliverConsensusOutput"
)

// NarwhalGatewayClient is the client API for NarwhalGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NarwhalGatewayClient interface {
	// SubmitTransaction is invoked by Ethereum Geth to submit Tx
	SubmitTransaction(ctx context.Context, in *Proposal, opts ...grpc.CallOption) (*ProposalResponse, error)
	// SubscribeConsensusOutput is invoked by Geth to subsribe ConsensusOutput
	SubscribeConsensusOutput(ctx context.Context, in *SubscribeConsensusOutputRequest, opts ...grpc.CallOption) (NarwhalGateway_SubscribeConsensusOutputClient, error)
	// DeliverConsensusOutput is invoked by NarwhalNode to deliver ConsensusOutput
	DeliverConsensusOutput(ctx context.Context, in *GatewayConsensusOutput, opts ...grpc.CallOption) (*DeliverConsensusOutputResponse, error)
}

type narwhalGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewNarwhalGatewayClient(cc grpc.ClientConnInterface) NarwhalGatewayClient {
	return &narwhalGatewayClient{cc}
}

func (c *narwhalGatewayClient) SubmitTransaction(ctx context.Context, in *Proposal, opts ...grpc.CallOption) (*ProposalResponse, error) {
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, NarwhalGateway_SubmitTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *narwhalGatewayClient) SubscribeConsensusOutput(ctx context.Context, in *SubscribeConsensusOutputRequest, opts ...grpc.CallOption) (NarwhalGateway_SubscribeConsensusOutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &NarwhalGateway_ServiceDesc.Streams[0], NarwhalGateway_SubscribeConsensusOutput_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &narwhalGatewaySubscribeConsensusOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NarwhalGateway_SubscribeConsensusOutputClient interface {
	Recv() (*SubscribeConsensusOutputResponse, error)
	grpc.ClientStream
}

type narwhalGatewaySubscribeConsensusOutputClient struct {
	grpc.ClientStream
}

func (x *narwhalGatewaySubscribeConsensusOutputClient) Recv() (*SubscribeConsensusOutputResponse, error) {
	m := new(SubscribeConsensusOutputResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *narwhalGatewayClient) DeliverConsensusOutput(ctx context.Context, in *GatewayConsensusOutput, opts ...grpc.CallOption) (*DeliverConsensusOutputResponse, error) {
	out := new(DeliverConsensusOutputResponse)
	err := c.cc.Invoke(ctx, NarwhalGateway_DeliverConsensusOutput_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NarwhalGatewayServer is the server API for NarwhalGateway service.
// All implementations should embed UnimplementedNarwhalGatewayServer
// for forward compatibility
type NarwhalGatewayServer interface {
	// SubmitTransaction is invoked by Ethereum Geth to submit Tx
	SubmitTransaction(context.Context, *Proposal) (*ProposalResponse, error)
	// SubscribeConsensusOutput is invoked by Geth to subsribe ConsensusOutput
	SubscribeConsensusOutput(*SubscribeConsensusOutputRequest, NarwhalGateway_SubscribeConsensusOutputServer) error
	// DeliverConsensusOutput is invoked by NarwhalNode to deliver ConsensusOutput
	DeliverConsensusOutput(context.Context, *GatewayConsensusOutput) (*DeliverConsensusOutputResponse, error)
}

// UnimplementedNarwhalGatewayServer should be embedded to have forward compatible implementations.
type UnimplementedNarwhalGatewayServer struct {
}

func (UnimplementedNarwhalGatewayServer) SubmitTransaction(context.Context, *Proposal) (*ProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedNarwhalGatewayServer) SubscribeConsensusOutput(*SubscribeConsensusOutputRequest, NarwhalGateway_SubscribeConsensusOutputServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeConsensusOutput not implemented")
}
func (UnimplementedNarwhalGatewayServer) DeliverConsensusOutput(context.Context, *GatewayConsensusOutput) (*DeliverConsensusOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverConsensusOutput not implemented")
}

// UnsafeNarwhalGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NarwhalGatewayServer will
// result in compilation errors.
type UnsafeNarwhalGatewayServer interface {
	mustEmbedUnimplementedNarwhalGatewayServer()
}

func RegisterNarwhalGatewayServer(s grpc.ServiceRegistrar, srv NarwhalGatewayServer) {
	s.RegisterService(&NarwhalGateway_ServiceDesc, srv)
}

func _NarwhalGateway_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NarwhalGatewayServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NarwhalGateway_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NarwhalGatewayServer).SubmitTransaction(ctx, req.(*Proposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _NarwhalGateway_SubscribeConsensusOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeConsensusOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NarwhalGatewayServer).SubscribeConsensusOutput(m, &narwhalGatewaySubscribeConsensusOutputServer{stream})
}

type NarwhalGateway_SubscribeConsensusOutputServer interface {
	Send(*SubscribeConsensusOutputResponse) error
	grpc.ServerStream
}

type narwhalGatewaySubscribeConsensusOutputServer struct {
	grpc.ServerStream
}

func (x *narwhalGatewaySubscribeConsensusOutputServer) Send(m *SubscribeConsensusOutputResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NarwhalGateway_DeliverConsensusOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayConsensusOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NarwhalGatewayServer).DeliverConsensusOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NarwhalGateway_DeliverConsensusOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NarwhalGatewayServer).DeliverConsensusOutput(ctx, req.(*GatewayConsensusOutput))
	}
	return interceptor(ctx, in, info, handler)
}

// NarwhalGateway_ServiceDesc is the grpc.ServiceDesc for NarwhalGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NarwhalGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narwhal_gateway.NarwhalGateway",
	HandlerType: (*NarwhalGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _NarwhalGateway_SubmitTransaction_Handler,
		},
		{
			MethodName: "DeliverConsensusOutput",
			Handler:    _NarwhalGateway_DeliverConsensusOutput_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeConsensusOutput",
			Handler:       _NarwhalGateway_SubscribeConsensusOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "narwhal-gateway.proto",
}

const (
	CommitNotifier_Notify_FullMethodName = "/narwhal_gateway.CommitNotifier/Notify"
)

// CommitNotifierClient is the client API for CommitNotifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommitNotifierClient interface {
	Notify(ctx context.Context, in *NarwhalCommitEvent, opts ...grpc.CallOption) (*NotifyResp, error)
}

type commitNotifierClient struct {
	cc grpc.ClientConnInterface
}

func NewCommitNotifierClient(cc grpc.ClientConnInterface) CommitNotifierClient {
	return &commitNotifierClient{cc}
}

func (c *commitNotifierClient) Notify(ctx context.Context, in *NarwhalCommitEvent, opts ...grpc.CallOption) (*NotifyResp, error) {
	out := new(NotifyResp)
	err := c.cc.Invoke(ctx, CommitNotifier_Notify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommitNotifierServer is the server API for CommitNotifier service.
// All implementations should embed UnimplementedCommitNotifierServer
// for forward compatibility
type CommitNotifierServer interface {
	Notify(context.Context, *NarwhalCommitEvent) (*NotifyResp, error)
}

// UnimplementedCommitNotifierServer should be embedded to have forward compatible implementations.
type UnimplementedCommitNotifierServer struct {
}

func (UnimplementedCommitNotifierServer) Notify(context.Context, *NarwhalCommitEvent) (*NotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}

// UnsafeCommitNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommitNotifierServer will
// result in compilation errors.
type UnsafeCommitNotifierServer interface {
	mustEmbedUnimplementedCommitNotifierServer()
}

func RegisterCommitNotifierServer(s grpc.ServiceRegistrar, srv CommitNotifierServer) {
	s.RegisterService(&CommitNotifier_ServiceDesc, srv)
}

func _CommitNotifier_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NarwhalCommitEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitNotifierServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommitNotifier_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitNotifierServer).Notify(ctx, req.(*NarwhalCommitEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// CommitNotifier_ServiceDesc is the grpc.ServiceDesc for CommitNotifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommitNotifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narwhal_gateway.CommitNotifier",
	HandlerType: (*CommitNotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _CommitNotifier_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "narwhal-gateway.proto",
}
