// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: narwhal-gateway.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderExtraPayload_NarwhalSignatureType int32

const (
	HeaderExtraPayload_ECDSA    HeaderExtraPayload_NarwhalSignatureType = 0
	HeaderExtraPayload_BLS12381 HeaderExtraPayload_NarwhalSignatureType = 1
)

// Enum value maps for HeaderExtraPayload_NarwhalSignatureType.
var (
	HeaderExtraPayload_NarwhalSignatureType_name = map[int32]string{
		0: "ECDSA",
		1: "BLS12381",
	}
	HeaderExtraPayload_NarwhalSignatureType_value = map[string]int32{
		"ECDSA":    0,
		"BLS12381": 1,
	}
)

func (x HeaderExtraPayload_NarwhalSignatureType) Enum() *HeaderExtraPayload_NarwhalSignatureType {
	p := new(HeaderExtraPayload_NarwhalSignatureType)
	*p = x
	return p
}

func (x HeaderExtraPayload_NarwhalSignatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderExtraPayload_NarwhalSignatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_narwhal_gateway_proto_enumTypes[0].Descriptor()
}

func (HeaderExtraPayload_NarwhalSignatureType) Type() protoreflect.EnumType {
	return &file_narwhal_gateway_proto_enumTypes[0]
}

func (x HeaderExtraPayload_NarwhalSignatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderExtraPayload_NarwhalSignatureType.Descriptor instead.
func (HeaderExtraPayload_NarwhalSignatureType) EnumDescriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{12, 0}
}

type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EthereumBlock  []byte `protobuf:"bytes,1,opt,name=ethereum_block,json=ethereumBlock,proto3" json:"ethereum_block,omitempty"`
	EthereumHeader []byte `protobuf:"bytes,2,opt,name=ethereum_header,json=ethereumHeader,proto3" json:"ethereum_header,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetEthereumBlock() []byte {
	if x != nil {
		return x.EthereumBlock
	}
	return nil
}

func (x *Proposal) GetEthereumHeader() []byte {
	if x != nil {
		return x.EthereumHeader
	}
	return nil
}

type ProposalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessOrFail string `protobuf:"bytes,1,opt,name=success_or_fail,json=successOrFail,proto3" json:"success_or_fail,omitempty"`
}

func (x *ProposalResponse) Reset() {
	*x = ProposalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalResponse) ProtoMessage() {}

func (x *ProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalResponse.ProtoReflect.Descriptor instead.
func (*ProposalResponse) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalResponse) GetSuccessOrFail() string {
	if x != nil {
		return x.SuccessOrFail
	}
	return ""
}

type GatewayCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header              []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	AggregatedSignature []byte `protobuf:"bytes,2,opt,name=aggregated_signature,json=aggregatedSignature,proto3" json:"aggregated_signature,omitempty"`
}

func (x *GatewayCertificate) Reset() {
	*x = GatewayCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCertificate) ProtoMessage() {}

func (x *GatewayCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCertificate.ProtoReflect.Descriptor instead.
func (*GatewayCertificate) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayCertificate) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GatewayCertificate) GetAggregatedSignature() []byte {
	if x != nil {
		return x.AggregatedSignature
	}
	return nil
}

// Each Payload represents a committed ethereum block
type GatewayBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *GatewayBatch) Reset() {
	*x = GatewayBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayBatch) ProtoMessage() {}

func (x *GatewayBatch) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayBatch.ProtoReflect.Descriptor instead.
func (*GatewayBatch) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayBatch) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ArrayOfCertificateAndBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate []*GatewayCertificate `protobuf:"bytes,1,rep,name=certificate,proto3" json:"certificate,omitempty"`
	Batch       []*GatewayBatch       `protobuf:"bytes,2,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *ArrayOfCertificateAndBatch) Reset() {
	*x = ArrayOfCertificateAndBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayOfCertificateAndBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayOfCertificateAndBatch) ProtoMessage() {}

func (x *ArrayOfCertificateAndBatch) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayOfCertificateAndBatch.ProtoReflect.Descriptor instead.
func (*ArrayOfCertificateAndBatch) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ArrayOfCertificateAndBatch) GetCertificate() []*GatewayCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *ArrayOfCertificateAndBatch) GetBatch() []*GatewayBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type GatewayCommittedSubDag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / The sequence of committed certificates.
	Certificates []*GatewayCertificate `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	// / The leader certificate responsible of committing this sub-dag.
	LeaderCertificate []byte `protobuf:"bytes,2,opt,name=leader_certificate,json=leaderCertificate,proto3" json:"leader_certificate,omitempty"`
	// SequenceNumber is the order determined in Narwhal
	SequenceNumber uint64 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
}

func (x *GatewayCommittedSubDag) Reset() {
	*x = GatewayCommittedSubDag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayCommittedSubDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCommittedSubDag) ProtoMessage() {}

func (x *GatewayCommittedSubDag) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCommittedSubDag.ProtoReflect.Descriptor instead.
func (*GatewayCommittedSubDag) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayCommittedSubDag) GetCertificates() []*GatewayCertificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *GatewayCommittedSubDag) GetLeaderCertificate() []byte {
	if x != nil {
		return x.LeaderCertificate
	}
	return nil
}

func (x *GatewayCommittedSubDag) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// / The output of Consensus, which includes all the batches for each certificate in the sub dag
// / It is sent to the the Adapter to execute using EVM
type GatewayConsensusOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SubDag is unmarshaled to CommittedSubDag
	SubDag []byte `protobuf:"bytes,1,opt,name=sub_dag,json=subDag,proto3" json:"sub_dag,omitempty"`
	// Batches is unmarshaled to ArrayOfCertificateAndBatch
	Batches            [][]byte `protobuf:"bytes,2,rep,name=batches,proto3" json:"batches,omitempty"`
	LeaderHeaderDigest []byte   `protobuf:"bytes,3,opt,name=leader_header_digest,json=leaderHeaderDigest,proto3" json:"leader_header_digest,omitempty"`
}

func (x *GatewayConsensusOutput) Reset() {
	*x = GatewayConsensusOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayConsensusOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConsensusOutput) ProtoMessage() {}

func (x *GatewayConsensusOutput) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConsensusOutput.ProtoReflect.Descriptor instead.
func (*GatewayConsensusOutput) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayConsensusOutput) GetSubDag() []byte {
	if x != nil {
		return x.SubDag
	}
	return nil
}

func (x *GatewayConsensusOutput) GetBatches() [][]byte {
	if x != nil {
		return x.Batches
	}
	return nil
}

func (x *GatewayConsensusOutput) GetLeaderHeaderDigest() []byte {
	if x != nil {
		return x.LeaderHeaderDigest
	}
	return nil
}

type SubscribeConsensusOutputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestorId string `protobuf:"bytes,1,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
}

func (x *SubscribeConsensusOutputRequest) Reset() {
	*x = SubscribeConsensusOutputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeConsensusOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeConsensusOutputRequest) ProtoMessage() {}

func (x *SubscribeConsensusOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeConsensusOutputRequest.ProtoReflect.Descriptor instead.
func (*SubscribeConsensusOutputRequest) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeConsensusOutputRequest) GetRequestorId() string {
	if x != nil {
		return x.RequestorId
	}
	return ""
}

type DeliverConsensusOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,4,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *DeliverConsensusOutputResponse) Reset() {
	*x = DeliverConsensusOutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverConsensusOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverConsensusOutputResponse) ProtoMessage() {}

func (x *DeliverConsensusOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverConsensusOutputResponse.ProtoReflect.Descriptor instead.
func (*DeliverConsensusOutputResponse) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *DeliverConsensusOutputResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

type SubscribeConsensusOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NarwhalSequenceNumber uint64   `protobuf:"varint,1,opt,name=narwhal_sequence_number,json=narwhalSequenceNumber,proto3" json:"narwhal_sequence_number,omitempty"`
	EthSequenceNumbers    []uint64 `protobuf:"varint,2,rep,packed,name=eth_sequence_numbers,json=ethSequenceNumbers,proto3" json:"eth_sequence_numbers,omitempty"`
	EthBlockDigest        [][]byte `protobuf:"bytes,3,rep,name=eth_block_digest,json=ethBlockDigest,proto3" json:"eth_block_digest,omitempty"`
}

func (x *SubscribeConsensusOutputResponse) Reset() {
	*x = SubscribeConsensusOutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeConsensusOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeConsensusOutputResponse) ProtoMessage() {}

func (x *SubscribeConsensusOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeConsensusOutputResponse.ProtoReflect.Descriptor instead.
func (*SubscribeConsensusOutputResponse) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeConsensusOutputResponse) GetNarwhalSequenceNumber() uint64 {
	if x != nil {
		return x.NarwhalSequenceNumber
	}
	return 0
}

func (x *SubscribeConsensusOutputResponse) GetEthSequenceNumbers() []uint64 {
	if x != nil {
		return x.EthSequenceNumbers
	}
	return nil
}

func (x *SubscribeConsensusOutputResponse) GetEthBlockDigest() [][]byte {
	if x != nil {
		return x.EthBlockDigest
	}
	return nil
}

type NarwhalCommitEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NarwhalSequenceNumber uint64   `protobuf:"varint,1,opt,name=narwhal_sequence_number,json=narwhalSequenceNumber,proto3" json:"narwhal_sequence_number,omitempty"`
	EthSequenceNumbers    []uint64 `protobuf:"varint,2,rep,packed,name=eth_sequence_numbers,json=ethSequenceNumbers,proto3" json:"eth_sequence_numbers,omitempty"`
	EthBlockDigest        [][]byte `protobuf:"bytes,3,rep,name=eth_block_digest,json=ethBlockDigest,proto3" json:"eth_block_digest,omitempty"`
	Extensions_           []byte   `protobuf:"bytes,4,opt,name=extensions_,json=extensions,proto3" json:"extensions_,omitempty"`
	LeaderHeaderDigest    []byte   `protobuf:"bytes,5,opt,name=leader_header_digest,json=leaderHeaderDigest,proto3" json:"leader_header_digest,omitempty"`
}

func (x *NarwhalCommitEvent) Reset() {
	*x = NarwhalCommitEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NarwhalCommitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarwhalCommitEvent) ProtoMessage() {}

func (x *NarwhalCommitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarwhalCommitEvent.ProtoReflect.Descriptor instead.
func (*NarwhalCommitEvent) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *NarwhalCommitEvent) GetNarwhalSequenceNumber() uint64 {
	if x != nil {
		return x.NarwhalSequenceNumber
	}
	return 0
}

func (x *NarwhalCommitEvent) GetEthSequenceNumbers() []uint64 {
	if x != nil {
		return x.EthSequenceNumbers
	}
	return nil
}

func (x *NarwhalCommitEvent) GetEthBlockDigest() [][]byte {
	if x != nil {
		return x.EthBlockDigest
	}
	return nil
}

func (x *NarwhalCommitEvent) GetExtensions_() []byte {
	if x != nil {
		return x.Extensions_
	}
	return nil
}

func (x *NarwhalCommitEvent) GetLeaderHeaderDigest() []byte {
	if x != nil {
		return x.LeaderHeaderDigest
	}
	return nil
}

type NotifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *NotifyResp) Reset() {
	*x = NotifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResp) ProtoMessage() {}

func (x *NotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResp.ProtoReflect.Descriptor instead.
func (*NotifyResp) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyResp) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

type HeaderExtraPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExtraVanity       []byte                                  `protobuf:"bytes,1,opt,name=extra_vanity,json=extraVanity,proto3" json:"extra_vanity,omitempty"`
	PoaSignature      []byte                                  `protobuf:"bytes,2,opt,name=poa_signature,json=poaSignature,proto3" json:"poa_signature,omitempty"`
	SigType           HeaderExtraPayload_NarwhalSignatureType `protobuf:"varint,3,opt,name=sig_type,json=sigType,proto3,enum=narwhal_gateway.HeaderExtraPayload_NarwhalSignatureType" json:"sig_type,omitempty"`
	NarwhalSignatures [][]byte                                `protobuf:"bytes,4,rep,name=narwhal_signatures,json=narwhalSignatures,proto3" json:"narwhal_signatures,omitempty"`
	SignerAddresses   [][]byte                                `protobuf:"bytes,5,rep,name=signer_addresses,json=signerAddresses,proto3" json:"signer_addresses,omitempty"`
	Extensions_       []byte                                  `protobuf:"bytes,6,opt,name=extensions_,json=extensions,proto3" json:"extensions_,omitempty"`
}

func (x *HeaderExtraPayload) Reset() {
	*x = HeaderExtraPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_gateway_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderExtraPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderExtraPayload) ProtoMessage() {}

func (x *HeaderExtraPayload) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_gateway_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderExtraPayload.ProtoReflect.Descriptor instead.
func (*HeaderExtraPayload) Descriptor() ([]byte, []int) {
	return file_narwhal_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *HeaderExtraPayload) GetExtraVanity() []byte {
	if x != nil {
		return x.ExtraVanity
	}
	return nil
}

func (x *HeaderExtraPayload) GetPoaSignature() []byte {
	if x != nil {
		return x.PoaSignature
	}
	return nil
}

func (x *HeaderExtraPayload) GetSigType() HeaderExtraPayload_NarwhalSignatureType {
	if x != nil {
		return x.SigType
	}
	return HeaderExtraPayload_ECDSA
}

func (x *HeaderExtraPayload) GetNarwhalSignatures() [][]byte {
	if x != nil {
		return x.NarwhalSignatures
	}
	return nil
}

func (x *HeaderExtraPayload) GetSignerAddresses() [][]byte {
	if x != nil {
		return x.SignerAddresses
	}
	return nil
}

func (x *HeaderExtraPayload) GetExtensions_() []byte {
	if x != nil {
		return x.Extensions_
	}
	return nil
}

var File_narwhal_gateway_proto protoreflect.FileDescriptor

var file_narwhal_gateway_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x5a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x74,
	0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x65,
	0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6f, 0x72, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x72, 0x46, 0x61, 0x69, 0x6c,
	0x22, 0x5f, 0x0a, 0x12, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31,
	0x0a, 0x14, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x28, 0x0a, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x1a,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x4f, 0x66, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x45, 0x0a, 0x0b, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x33, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x22, 0xb9, 0x01, 0x0a, 0x16, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x53, 0x75, 0x62, 0x44, 0x61,
	0x67, 0x12, 0x47, 0x0a, 0x0c, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x6c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x7d, 0x0a, 0x16, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x5f, 0x64, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73,
	0x75, 0x62, 0x44, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12,
	0x30, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x22, 0x44, 0x0a, 0x1f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0xb6, 0x01,
	0x0a, 0x20, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x15, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x74,
	0x68, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x12, 0x65, 0x74, 0x68, 0x53, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x10,
	0x65, 0x74, 0x68, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x65, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0xfb, 0x01, 0x0a, 0x12, 0x4e, 0x61, 0x72, 0x77, 0x68,
	0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a,
	0x17, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x15,
	0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x12, 0x65, 0x74, 0x68, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x74, 0x68, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x0e, 0x65, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x12, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0xdd, 0x02, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x76, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x72, 0x61, 0x56, 0x61, 0x6e, 0x69, 0x74, 0x79,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x61, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x6f, 0x61, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61,
	0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4e, 0x61, 0x72,
	0x77, 0x68, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x07, 0x73, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x6e, 0x61,
	0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x11, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x5f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2f, 0x0a, 0x14, 0x4e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x43, 0x44, 0x53, 0x41, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x4c, 0x53, 0x31,
	0x32, 0x33, 0x38, 0x31, 0x10, 0x01, 0x32, 0xdb, 0x02, 0x0a, 0x0e, 0x4e, 0x61, 0x72, 0x77, 0x68,
	0x61, 0x6c, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x51, 0x0a, 0x11, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x1a, 0x21, 0x2e, 0x6e, 0x61, 0x72, 0x77,
	0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a,
	0x18, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x30, 0x2e, 0x6e, 0x61, 0x72, 0x77,
	0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6e, 0x61,
	0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x72, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x27, 0x2e, 0x6e, 0x61, 0x72,
	0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x1a, 0x2f, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5c, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x23, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x4e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x5f,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_narwhal_gateway_proto_rawDescOnce sync.Once
	file_narwhal_gateway_proto_rawDescData = file_narwhal_gateway_proto_rawDesc
)

func file_narwhal_gateway_proto_rawDescGZIP() []byte {
	file_narwhal_gateway_proto_rawDescOnce.Do(func() {
		file_narwhal_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_narwhal_gateway_proto_rawDescData)
	})
	return file_narwhal_gateway_proto_rawDescData
}

var file_narwhal_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_narwhal_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_narwhal_gateway_proto_goTypes = []interface{}{
	(HeaderExtraPayload_NarwhalSignatureType)(0), // 0: narwhal_gateway.HeaderExtraPayload.NarwhalSignatureType
	(*Proposal)(nil),                         // 1: narwhal_gateway.Proposal
	(*ProposalResponse)(nil),                 // 2: narwhal_gateway.ProposalResponse
	(*GatewayCertificate)(nil),               // 3: narwhal_gateway.GatewayCertificate
	(*GatewayBatch)(nil),                     // 4: narwhal_gateway.GatewayBatch
	(*ArrayOfCertificateAndBatch)(nil),       // 5: narwhal_gateway.ArrayOfCertificateAndBatch
	(*GatewayCommittedSubDag)(nil),           // 6: narwhal_gateway.GatewayCommittedSubDag
	(*GatewayConsensusOutput)(nil),           // 7: narwhal_gateway.GatewayConsensusOutput
	(*SubscribeConsensusOutputRequest)(nil),  // 8: narwhal_gateway.SubscribeConsensusOutputRequest
	(*DeliverConsensusOutputResponse)(nil),   // 9: narwhal_gateway.DeliverConsensusOutputResponse
	(*SubscribeConsensusOutputResponse)(nil), // 10: narwhal_gateway.SubscribeConsensusOutputResponse
	(*NarwhalCommitEvent)(nil),               // 11: narwhal_gateway.NarwhalCommitEvent
	(*NotifyResp)(nil),                       // 12: narwhal_gateway.NotifyResp
	(*HeaderExtraPayload)(nil),               // 13: narwhal_gateway.HeaderExtraPayload
}
var file_narwhal_gateway_proto_depIdxs = []int32{
	3,  // 0: narwhal_gateway.ArrayOfCertificateAndBatch.certificate:type_name -> narwhal_gateway.GatewayCertificate
	4,  // 1: narwhal_gateway.ArrayOfCertificateAndBatch.batch:type_name -> narwhal_gateway.GatewayBatch
	3,  // 2: narwhal_gateway.GatewayCommittedSubDag.certificates:type_name -> narwhal_gateway.GatewayCertificate
	0,  // 3: narwhal_gateway.HeaderExtraPayload.sig_type:type_name -> narwhal_gateway.HeaderExtraPayload.NarwhalSignatureType
	1,  // 4: narwhal_gateway.NarwhalGateway.SubmitTransaction:input_type -> narwhal_gateway.Proposal
	8,  // 5: narwhal_gateway.NarwhalGateway.SubscribeConsensusOutput:input_type -> narwhal_gateway.SubscribeConsensusOutputRequest
	7,  // 6: narwhal_gateway.NarwhalGateway.DeliverConsensusOutput:input_type -> narwhal_gateway.GatewayConsensusOutput
	11, // 7: narwhal_gateway.CommitNotifier.Notify:input_type -> narwhal_gateway.NarwhalCommitEvent
	2,  // 8: narwhal_gateway.NarwhalGateway.SubmitTransaction:output_type -> narwhal_gateway.ProposalResponse
	10, // 9: narwhal_gateway.NarwhalGateway.SubscribeConsensusOutput:output_type -> narwhal_gateway.SubscribeConsensusOutputResponse
	9,  // 10: narwhal_gateway.NarwhalGateway.DeliverConsensusOutput:output_type -> narwhal_gateway.DeliverConsensusOutputResponse
	12, // 11: narwhal_gateway.CommitNotifier.Notify:output_type -> narwhal_gateway.NotifyResp
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_narwhal_gateway_proto_init() }
func file_narwhal_gateway_proto_init() {
	if File_narwhal_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_narwhal_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayOfCertificateAndBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayCommittedSubDag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayConsensusOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeConsensusOutputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverConsensusOutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeConsensusOutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NarwhalCommitEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_gateway_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderExtraPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_narwhal_gateway_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_narwhal_gateway_proto_goTypes,
		DependencyIndexes: file_narwhal_gateway_proto_depIdxs,
		EnumInfos:         file_narwhal_gateway_proto_enumTypes,
		MessageInfos:      file_narwhal_gateway_proto_msgTypes,
	}.Build()
	File_narwhal_gateway_proto = out.File
	file_narwhal_gateway_proto_rawDesc = nil
	file_narwhal_gateway_proto_goTypes = nil
	file_narwhal_gateway_proto_depIdxs = nil
}
