[package]
name = "sslab-core"
version = "0.1.0"
authors = ["Donghyeon Ryu <donghyeonryu@postech.ac.kr>"]
edition = "2021"
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
anyhow = { workspace = true, features = ["backtrace"] }
# arc-swap.workspace = true
async-trait.workspace = true
bcs.workspace = true
bytes.workspace = true
cfg-if.workspace = true
chrono.workspace = true
clap = "2.34"
dashmap.workspace = true
eyre.workspace = true
futures.workspace = true
itertools.workspace = true
num_cpus.workspace = true
# once_cell.workspace = true
parking_lot.workspace = true
prometheus.workspace = true
# rand.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
# signature.workspace = true
# tempfile.workspace = true
# thiserror.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
# tokio-retry.workspace = true
# tokio-stream.workspace = true
tracing.workspace = true
url.workspace = true
fastcrypto.workspace = true

mysten-metrics.workspace = true
config = { path = "../../narwhal/config", package = "narwhal-config" }
crypto = { path = "../../narwhal/crypto", package = "narwhal-crypto" }
types = { path = "../../narwhal/types", package = "narwhal-types" }
executor = { path = "../../narwhal/executor", package = "narwhal-executor" }
node = { path = "../../narwhal/node", package = "narwhal-node" }
storage = { path = "../../narwhal/storage", package = "narwhal-storage" }
# narwhal-config.workspace = true
# narwhal-crypto.workspace = true
# narwhal-executor.workspace = true
# narwhal-network.workspace = true
# narwhal-types.workspace = true
# narwhal-worker.workspace = true
# shared-crypto.workspace = true
# sui-archival.workspace = true
sui-config.workspace = true
# sui-framework.workspace = true
# sui-swarm-config.workspace = true
# sui-genesis-builder.workspace = true
sui-keys.workspace = true
# sui-json-rpc-types.workspace = true
sui-macros.workspace = true
sui-network.workspace = true
sui-protocol-config.workspace = true
# sui-simulator.workspace = true
# sui-storage.workspace = true
sui-types.workspace = true
tracing-subscriber.workspace = true
# workspace-hack.workspace = true
sui-core.workspace = true
telemetry-subscribers.workspace = true


sslab-execution = { workspace = true, features = ["benchmark"] }
sslab-execution-serial = { workspace = true }
# sslab-execution-optme = { workspace = true, optional = true }
fail = "0.5.1"
prost = "0.11"
rand = "0.8.5"
tonic = "0.8.2"
bincode = "1.3.3"

[dev-dependencies]
criterion.workspace = true
ethers-core = "^2.0.0"
ethers-providers = { version = "^2.0.0" }
rayon = "1.8.0"

[features]
benchmark = ["sslab-execution/benchmark"]

# execution model
# optme = ["sslab-execution-optme"]
serial = []

[[bin]]
name = "sslab-narwhal-node"
path = "src/main.rs"

[[bench]]
name = "decoding"
harness = false
