[package]
name = "sslab-core"
version = "0.1.0"
authors = ["Donghyeon Ryu <donghyeonryu@postech.ac.kr>"]
edition = "2021"
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
anyhow = { workspace = true, features = ["backtrace"] }
async-trait.workspace = true
bcs.workspace = true
bytes.workspace = true
cfg-if.workspace = true
chrono.workspace = true
clap = "2.34"
dashmap.workspace = true
eyre.workspace = true
futures.workspace = true
itertools.workspace = true
num_cpus.workspace = true
parking_lot.workspace = true
prometheus.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true
url.workspace = true
fastcrypto.workspace = true

mysten-metrics.workspace = true
config = { path = "../../narwhal/config", package = "narwhal-config" }
crypto = { path = "../../narwhal/crypto", package = "narwhal-crypto" }
types = { path = "../../narwhal/types", package = "narwhal-types" }
executor = { path = "../../narwhal/executor", package = "narwhal-executor" }
node = { path = "../../narwhal/node", package = "narwhal-node" }
storage = { path = "../../narwhal/storage", package = "narwhal-storage" }

sui-keys.workspace = true
sui-types.workspace = true
tracing-subscriber.workspace = true
telemetry-subscribers.workspace = true


sslab-execution = { workspace = true, features = ["benchmark"] }
sslab-execution-serial = { workspace = true }
# sslab-execution-optme = { workspace = true, optional = true }
sslab-p2p.workspace = true
reth.workspace = true


secp256k1 = "0.27.0"
fail = "0.5.1"
prost = "0.11"
rand = "0.8.5"
tonic = "0.8.2"
bincode = "1.3.3"

jsonrpsee = { version = "0.21", features = ["server"] }

[dev-dependencies]
criterion.workspace = true
ethers-core = "^2.0.0"
ethers-providers = { version = "^2.0.0" }
rayon = "1.8.0"

[features]
benchmark = ["sslab-execution/benchmark", "node/benchmark"]

# execution model
# optme = ["sslab-execution-optme"]
serial = []

[[bin]]
name = "sslab-narwhal-node"
path = "src/main.rs"

[[bench]]
name = "decoding"
harness = false
