[Eth]
NetworkId = 423423
# "full" mode executes every block from the genesis and only maintain the latest 128 blocks.
# "snap" mode downloads and verifies headers. and download block bodies and receipts, and (in parallel) download raw state data and build state trie.
SyncMode = "full"
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
TxLookupLimit = 2350000
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 154
TrieCleanCacheJournal = "triecache"
TrieCleanCacheRejournal = 3600000000000
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 102
Preimages = false
FilterLogCacheSize = 32
EnablePreimageRecording = false
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 1e+00

[Eth.Miner]
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 2000000000
NewPayloadTimeout = 2000000000

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 5120
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 500000000000
IgnorePrice = 2

[Node]
DataDir = "/home/sslab/integ/eth-data"
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 40000
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false # set to true to disable discovery
BootstrapNodes = [
    "enode://4d0de5ca011ac031c4570aa27346d7acd77e7ac1044487f2e8654b43a2a4a4bee9e76c7ae2aeb064f427a8732b80776a86dc5c2ce36ac36517a028b14c45e639@127.0.0.1:30304",
]
BootstrapNodesV5 = []
# enode URLs of static-nodes.json are added here 
StaticNodes = []
TrustedNodes = [
    "enode://4d0de5ca011ac031c4570aa27346d7acd77e7ac1044487f2e8654b43a2a4a4bee9e76c7ae2aeb064f427a8732b80776a86dc5c2ce36ac36517a028b14c45e639@127.0.0.1:30304",
]
ListenAddr = ":30300" # default port is 30303
DiscAddr = ":30300"
EnableMsgEvents = true

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Metrics]
HTTP = "127.0.0.1"
Port = 6060
InfluxDBEndpoint = "http://localhost:8086"
InfluxDBDatabase = "geth"
InfluxDBUsername = "test"
InfluxDBPassword = "test"
InfluxDBTags = "host=localhost"
InfluxDBToken = "test"
InfluxDBBucket = "geth"
InfluxDBOrganization = "geth"
